sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build
  - docker-compose run --rm dev composer install
  - docker-compose run --rm dev composer require squizlabs/php_codesniffer
script:
  - docker-compose run --rm dev ./vendor/bin/phpunit tests/
  - docker-compose run --rm dev vendor/bin/phpcs --standard=psr2 -n --ignore=vendor --extensions=php .
after_success:
  - docker images
